version: '3.9'

services:

  glimpse-api:
    container_name: glimpse
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gateway
    depends_on:
        - gateway
        - auth
        - profiles
        - messenger

  gateway:
    container_name: gateway
    image: maxage/gandalf-gateway:master
    depends_on:
      - profiles
      - auth
    restart: unless-stopped
    networks:
      - gateway

  auth:
    container_name: auth
    image: maxage/auth:master
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres
      - gateway

  profiles:
    container_name: profiles
    image: maxage/profiles:master
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres
      - gateway

  messenger:
    container_name: messenger
    image: ghcr.io/archiesw/messenger:v0.5.0-latest
    environment:
      DB_HOST: scylla-node1
      DB_PORT: 9042
    depends_on:
      - scylla-node1
    networks:
      gateway:

  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:5.2.14
    ports:
      - "9042:9042"
    command: --memory 750M
    volumes:
      - "./schema.cql:/schema.cql"
    networks:
      gateway:

  script_runner:
    image: scylladb/scylla:5.2.14
    depends_on:
      - scylla-node1
    restart: "no"
    volumes:
      - "./schema.cql:/schema.cql"
    network_mode: "service:scylla-node1"
    environment:
      CQLSH_HOST: scylla-node1
    entrypoint: [ "bash", "-c", "sleep 40 && cqlsh -f /schema.cql"]

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: glimpse
      POSTGRES_USER: glimpse
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres
      - ./tables.up.sql:/docker-entrypoint-initdb.d/init.sql # on Windows change to ".\tables.up.sql"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
  gateway:
    driver: bridge