version: '3.9'

services:

  glimpse-api:
    container_name: glimpse
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - gateway
      - s3
    depends_on:
      - gateway
      - auth
      - profiles
      - messenger
      - media

  gateway:
    container_name: gateway
    image: maxage/gandalf-gateway:v0.0.2
    depends_on:
      - profiles
      - auth
    restart: unless-stopped
    networks:
      - gateway

  auth:
    container_name: auth
    image: maxage/auth:v0.0.1
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres
      - gateway

  profiles:
    container_name: profiles
    image: maxage/profiles:v0.0.2-alpha
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - postgres
      - gateway

  reactions:
    container_name: reactions
    image: devarchie/reactions:v0.1.0
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: glimpse
      POSTGRES_USER: glimpse
      POSTGRES_PWD: password
      PROFILE_SERVICE_GRPC_HOST: profiles
      PROFILE_SERVICE_GRPC_PORT: 8080
      MESSENGER_URL: http://messenger:8081
    depends_on:
      - postgres
      - profiles
      - messenger
    networks:
      gateway:
      postgres:

  messenger:
    container_name: messenger
    image: devarchie/messenger:v0.6.3
    environment:
      DB_HOST: scylla-node1
      DB_PORT: 9042
      PROFILE_SERVICE_GRPC_HOST: profiles
      PROFILE_SERVICE_GRPC_PORT: 8080
    depends_on:
      - scylla-node1
      - profiles
    networks:
      gateway:

  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:5.2.14
    ports:
      - "9042:9042"
    command: --memory 750M
    volumes:
      - "./schema.cql:/schema.cql"
    networks:
      gateway:

  script_runner:
    image: scylladb/scylla:5.2.14
    depends_on:
      - scylla-node1
    restart: "no"
    volumes:
      - "./schema.cql:/schema.cql"
    network_mode: "service:scylla-node1"
    environment:
      CQLSH_HOST: scylla-node1
    entrypoint: [ "bash", "-c", "sleep 40 && cqlsh -f /schema.cql"]

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DATABASE: glimpse
      POSTGRES_USER: glimpse
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres
      - ./tables.up.sql:/docker-entrypoint-initdb.d/init.sql # on Windows change to ".\tables.up.sql"
    restart: unless-stopped
    networks:
      - postgres

  media:
    container_name: media
    image: maxage/media:v0.0.1-alpha
    depends_on:
      - minio
    restart: unless-stopped
    networks:
      - s3
      - gateway

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    command: server /data
    volumes:
      - minio-data:/data
    networks:
      - s3

volumes:
  minio-data:

networks:
  postgres:
    driver: bridge
  gateway:
    driver: bridge
  s3:
    driver: bridge
