apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: maxage/gandalf-gateway:v0.1.0
          ports:
            - containerPort: 3000
          env:
            - name: API_ADDRESS
              value: "0.0.0.0:3000"
            - name: PROFILES_ADDRESS
              value: "profiles:8080"
            - name: PROFILES_ENABLE_TLS
              value: "false"
            - name: AUTH_ADDRESS
              value: "auth:8081"
            - name: AUTH_ENABLE_TLS
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: gateway-port
      port: 3000
      targetPort: 3000
  type: LoadBalancer
