apiVersion: apps/v1
kind: Deployment
metadata:
  name: glimpse-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glimpse-api
  template:
    metadata:
      labels:
        app: glimpse-api
    spec:
      containers:
        - name: glimpse
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: glimpse-nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glimpse-nginx-config
data:
  nginx.conf: |
    events {
        worker_connections  1024;
    }

    http {
        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }

        server {

            listen 80;

            # Define a location block for /api/v0/auth requests
            location ~ ^/api/v0/auth {
                proxy_pass http://gateway:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Define a location block for /api/v0/user/*/profile requests
            location ~ ^/api/v0/users/[^/]+/profile {
                proxy_pass http://gateway:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Define a location block for /api/v0/user/*/prompts requests
            location ~ ^/api/v0/users/[^/]+/prompts {
                proxy_pass http://gateway:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Define a location block for /api/v0/users/*/messages requests
            location ~ ^/users/[^/]+/messages {
                proxy_pass http://messenger:8081;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Define a location block for /api/v0/users/*/messages requests
            location ~ ^/users/[^/]+/reactions {
                proxy_pass http://reactions:8081;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Define a location block for WebSocket connections
            location /ws {
                proxy_pass http://messenger:8081;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header Host $host;
            }

            # Define a location block for /api/v0/users/*/messages requests
            location ~ ^/users/[^/]+/companions {
                proxy_pass http://messenger:8081;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Define a location block for S3 requests
            location ~ ^/media/[^/]+ {
                proxy_pass http://minio:9000;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Define a location block for /swagger requests
            location ~ ^/swagger {
                proxy_pass http://gateway:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Generic location block to catch any other /api/v0/ requests
            location ~ ^/api/v0/ {
                # You can define a default proxy_pass here if needed
                # For example, to proxy to a default service
                # proxy_pass http://default-service:8080;
                # Or simply return a 404 if no specific service is defined for the request
                return 404;
            }

        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: glimpse-api
spec:
  selector:
    app: glimpse-api
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31249
  type: LoadBalancer
