apiVersion: apps/v1
kind: Deployment
metadata:
  name: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
        - name: media
          image: maxage/media:v0.1.0
          ports:
            - containerPort: 8082
          env:
            - name: API_ADDRESS
              value: "0.0.0.0:8082"
            - name: S3_ADDRESS
              value: "minio:9000"
            - name: S3_ACCESS_KEY
              value: "accesskey"
            - name: S3_SECRET_KEY
              value: "secretkey"
            - name: S3_BUCKET
              value: "media"
            - name: S3_POLICY_FILE
              value: "./s3-policy.json"
            - name: API_PUBLIC_HOST
              value: "87.242.102.149:31249"
          resources:
            limits:
              cpu: 1m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: media
spec:
  selector:
    app: media
  ports:
    - name: media-grpc-port
      protocol: TCP
      port: 8082
  type: ClusterIP
