apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
        - name: messenger
          image: devarchie/messenger:v0.6.3
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: "scylla-node1"
            - name: DB_PORT
              value: "9042"
            - name: PROFILE_SERVICE_GRPC_HOST
              value: "profiles"
            - name: PROFILE_SERVICE_GRPC_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: messenger
spec:
  selector:
    app: messenger
  ports:
    - name: messenger-port
      port: 8081
      targetPort: 8081
  type: ClusterIP
