apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ROOT_USER
              value: "accesskey"
            - name: MINIO_ROOT_PASSWORD
              value: "secretkey"
          command: ["minio", "server", "/data"]
          volumeMounts:
            - name: minio-data
              mountPath: "/data"
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: minio-port
      port: 9000
      targetPort: 9000
  type: ClusterIP
