apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DATABASE
          value: glimpse
        - name: POSTGRES_USER
          value: glimpse
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: postgres-data
          mountPath: /data/postgres
      - name: postgres-exporter
        image: quay.io/prometheuscommunity/postgres-exporter
        ports:
          - containerPort: 9187
        env:
          - name: DATA_SOURCE_NAME
            value: "postgresql://glimpse:password@localhost:5432/glimpse?sslmode=disable"
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
spec:
  selector:
    app: postgres
  ports:
    - name: postgres-exporter
      port: 9187
      targetPort: 9187
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv0001/

