apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profiles
  template:
    metadata:
      labels:
        app: profiles
    spec:
      containers:
        - name: profiles
          image: maxage/profiles:v0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "glimpse"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "glimpse"
            - name: POSTGRES_SSL_MODE
              value: "disable"
            - name: API_ADDRESS
              value: "0.0.0.0:8080"
            - name: MEDIA_ADDRESS
              value: "media:8082"
          resources:
            limits:
              cpu: 1m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: profiles
spec:
  selector:
    app: profiles
  ports:
    - name: profiles-port
      port: 8080
      targetPort: 8080
  type: ClusterIP
