apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: "prometheus"
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.5
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: "/etc/prometheus/prometheus.yml"
              subPath: prometheus.yml
            - name: prometheus-data
              mountPath: "/prometheus"
          resources:
            limits:
              cpu: 100m
              memory: 750Mi
      volumes:
        - name: prometheus-config
          configMap:
            name: glimpse-prometheus-config
  volumeClaimTemplates:
    - metadata:
        name: prometheus-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glimpse-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    
    scrape_configs:
      - job_name: 'messenger'
        metrics_path: /metrics
        static_configs:
          - targets:
              - messenger:8081
              
      - job_name: 'reactions'
        metrics_path: /metrics
        static_configs:
          - targets:
              - reactions:8081
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - name: prometheus-port
      port: 9090
      targetPort: 9090
      nodePort: 31250
  type: NodePort

