apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactions
  template:
    metadata:
      labels:
        app: reactions
    spec:
      containers:
        - name: reactions
          image: devarchie/reactions:v0.1.0
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "glimpse"
            - name: POSTGRES_USER
              value: "glimpse"
            - name: POSTGRES_PWD
              value: "password"
            - name: PROFILE_SERVICE_GRPC_HOST
              value: "profiles"
            - name: PROFILE_SERVICE_GRPC_PORT
              value: "8080"
            - name: MESSENGER_URL
              value: "http://messenger:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: reactions
spec:
  selector:
    app: reactions
  ports:
    - name: reactions-port
      port: 8081
      targetPort: 8081
  type: ClusterIP
