apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scylla-node1
spec:
  serviceName: "scylla-node1"
  replicas: 1
  selector:
    matchLabels:
      app: scylla-node1
  template:
    metadata:
      labels:
        app: scylla-node1
    spec:
      containers:
      - name: scylla-node1
        image: scylladb/scylla:5.2.14
        ports:
        - containerPort: 9042
        volumeMounts:
        - name: scylla-data
          mountPath: "/var/lib/scylla"
        resources:
          limits:
            cpu: 100m
            memory: 750Mi
  volumeClaimTemplates:
  - metadata:
      name: scylla-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: scylla-node1
spec:
  selector:
    app: scylla-node1
  ports:
  - name: scylla-port
    port: 9042
    targetPort: 9042
    nodePort: 30000
  type: NodePort

